### ISSUE TITLE
yield* is not properly captured inside of expressions

### ISSUE THREAD

**Issue by bmeck** [facebook/regenerator#151]
The following code does not transform as expected:

``` js
function* one() {return 1};
function* two() {return yield* one() + yield* one(); };
var get=two();
var val = get.next();
var results = [val];
while (val.done == false) {
  val = get.next();
  results.push(val);
}
console.log(results);
```

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
