### ISSUE TITLE
Invalid completion record on BreakStatement with label

### ISSUE THREAD

**Issue by sebmck** [facebook/regenerator#162]
`invalid completion record: {"type":"break","target":null}`

```javascript
var i = 0;
var s = '';

function* f() {
  s += 'a';
  while(i++ < 3) {
    s += 'b';
    label1: {
      s += 'c';
      break label1;
      s += 'd';
    }
    s += 'e';
  }
  s += 'f';
}

var g = f();
g.next();
assert.equal(s, 'abcebcebcef');
```

**Comment by sebmck** [comment]
Looks like it's due to the leap manager trying to resolve it to a loop when any expression can be in a label statement.

**Comment by benjamn** [comment]
What's the expected behavior? Can a labeled `break` statement break to a labeled statement that isn't a loop?

**Comment by sebmck** [comment]
Looks like it just breaks the current block so for example in the example code code `s += 'd';` after `break label1;` never gets ran. Also for some context the example is taken from the [traceur test suite](https://github.com/google/traceur-compiler/blob/master/test/feature/Yield/LabelledBlockGenerator.js).

**Comment by benjamn** [comment]
Interesting!

**Comment by sebmck** [comment]
@benjamn Great! Unrelated question but have the generator error messages been standardised? I'm running 6to5 against the Traceur tests (which is how I found this bug) and the error messages don't match up which isn't that big of a deal but just thought I'd ask.

**Comment by benjamn** [comment]
Most if not all errors in the generator spec just say "if X then throw a TypeError" with no specified message. I've tried to keep compatibility with V8 just so the tests work in Node v0.11, but maybe I'm over-testing those error messages…

**Comment by lukasmlady** [comment]
Another `invalid completion record: {"type":"break","target":null}`:

```js
  go(function*() {
    // Enter mini event loop.
    eventLoop:
    while(true) {
      let {channel, value} = yield alts([stickiness, killChan]);

      switch(channel) {
        // When the stickiness changes.
        case stickiness:
          $navItems
            .find(".js-siteNavItemIcon")
            .each((idx, el) => resetIcon($(el), state.isSticky));

          break;

        case killChan:
          break eventLoop;
      }
    }
  });
```

If I remove the `.each((idx, el) => resetIcon($(el), state.isSticky));` line, it works - so the problem is the arrow function.

**Comment by benjamn** [comment]
@lukasmlady would you mind minimizing that example as far as possible (if it isn't already minimal) and opening a new issue? I think this bug might have a distinct root cause.

**Comment by lukasmlady** [comment]
@benjamn yep, will do.

**Comment by lukasmlady** [comment]
@benjamn Created #169.
