### ISSUE TITLE
Runtime defaults to creating a global variable

### ISSUE THREAD

**Issue by appden** [facebook/regenerator#166]
It's quite unfortunate that the runtime is not easy to package up as self-contained module. It seems to me that if the `exports` variable is available, then there should be no need to create the global variable.

I'm creating a self-contained library with generators, and it would be great to not have to manually delete this variable.

**Comment by sebmck** [comment]
This would also be a good supplement to the [core aliasing](https://6to5.org/docs/usage/transformers/#core-aliasing) behaviour of 6to5. It'd allow library authors to use generators with 6to5 and have the regenerator runtime imported into the local variable scope so it wouldn't leak.

**Comment by benjamn** [comment]
I think this might be a potential answer to my recent question: https://github.com/facebook/regenerator/issues/165#issuecomment-69844978

**Comment by benjamn** [comment]
Are you defining a local variable called `regeneratorRuntime`? Or do we need to generate a different expression for referring to the runtime? It shouldn't be too hard to make that configurable, if need be.

**Comment by sebmck** [comment]
@benjamn Ideally it'd be great to be able to go `var regeneratorRuntime = require("regenerator/foobar");`.

**Comment by appden** [comment]
@benjamn for my case, I wouldn't need that be configurable, so that could a separate issue.

I'm using this configuration with `browserify` to accomplish what I need:
```
insertGlobalVars: {
  regeneratorRuntime: function() {
    return "require('regenerator/runtime')"
  }
}
```

**Comment by fkling** [comment]
I think it should be made clear somewhere that the module still has to be assigned to the variable `regeneratorRuntime` (that's the case, right?).

**Comment by benjamn** [comment]
That's true, but the failure mode is that generated code will make undefined reference to `regeneratorRuntime`, which is a pretty easy problem to diagnose? Is that wishful thinking on my part?

**Comment by fkling** [comment]
That is true. But having to run into the issue in the first place to find out the name to use (which requires inspecting the generated code) can be discouraging. Personally I would be annoyed if I had to find out that way.

Either way, I think it would be worth extending the readme with an example that shows how to include the runtime "manually" (not via `--include-runtime`).
