### ISSUE TITLE
Throw with includeRuntime

### ISSUE THREAD

**Issue by popomore** [facebook/regenerator#168]
`regenerator -r test.js`

test.js

```
function *test () {yield 3};test().next().value;
```

- regenerator version: 0.8.6 
- test in node 0.10.6 and 0.11.12

**Comment by popomore** [comment]
Passed in 0.8.3

**Comment by popomore** [comment]
I found problem in this commit

2be435b3113d9c4709ad5cf60290280964c0154f#diff-d38265e97c3ccd439ad48d0460d8e9dcR31

**Comment by benjamn** [comment]
@popomore Thanks for catching that!

**Comment by popomore** [comment]
:smile:

**Comment by popomore** [comment]
Add testcase for includeRuntime?

**Comment by benjamn** [comment]
Good idea. I added this simple test which would have caught this problem: 986b4301aca3a4c0196a3dd06dc25b6819cd2ccd
