### ISSUE TITLE
Transformed generator function declarations cause scope conflict

### ISSUE THREAD

**Issue by sebmck** [facebook/regenerator#170]
```javascript
function* foo() {
  console.log(foo);
}

var bar = foo;
var foo = 1;
bar().next();
```

Should output `1` but instead outputs the actual function due to different function expression semantics.

**Comment by benjamn** [comment]
This is tricky because we need `foo` to be a reliable reference to the function when we pass it as the second argument to `regeneratorRuntime.wrap`:
```js
var foo = regeneratorRuntime.mark(function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    // ...
  }, foo, this); // This foo needs to refer to the function even if the var is reassigned.
});
```
It's tempting to use something like `arguments.callee`, but that won't work in strict mode.

Ideally, instead of transforming
```js
function* foo() {
  console.log(foo);
}
```
into
```js
// Note that foo becomes a FunctionExpression here.
var foo = regeneratorRuntime.mark(function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    // ...
  }, foo, this);
});
```
I'd like to go back to something like:
```js
// At top of enclosing block:
regeneratorRuntime.mark(foo);
// ...
// Leave the function declaration in the original location:
function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    // ...
  }, foo, this); // This foo is now vulnerable to renaming!
}
```
It seems like we have to store the original `foo` in a temporary variable at the time when `regeneratorRuntime.mark(foo)` is called:
```js
var foo$marked$0 = regeneratorRuntime.mark(foo);
// ...
function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    // ...
  }, foo$marked$0, this);
}
```
Can you think of a better way to do this?

**Comment by benjamn** [comment]
If we go in this direction, it's also tempting to let `regeneratorRuntime.mark` take multiple arguments, so we don't have to keep emitting it for every generator `FunctionDeclaration`:
```js
// The .mark method returns an array of its original arguments:
var marked$0 = regeneratorRuntime.mark(foo, bar, baz);
// ...
function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    // ...
  }, marked$0[0], this);
}
```

**Comment by benjamn** [comment]
Another option that doesn't change the current interface of `regeneratorRuntime.mark`:
```js
var funDecls$0 = [foo, bar, baz].map(regeneratorRuntime.mark);
// ...
function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    // ...
  }, funDecls$0[0], this);
}
```

**Comment by sebmck** [comment]
I'm not sure if there's a practical/elegant solution, just thought I'd report it so it's documented somewhere.

**Comment by benjamn** [comment]
@sebmck of course (and thanks)! Just trying to get my thoughts written down in case I don't get to this immediately.
