### ISSUE TITLE
Support await* delegation

### ISSUE THREAD

**Issue by RReverser** [facebook/regenerator#171]
Would be nice to have this feature from [await* and parallelism](https://github.com/lukehoban/ecmascript-asyncawait#await-and-parallelism) section of async/await proposal:

> It has been suggested that the syntax could be reused for different semantics - sugar for Promise.all. This would accept a value that is an array of Promises, and would (asynchronously) return an array of values returned by the promises. This is expected to be one of the most common Promise-related oprerations that would not yet have syntax sugar after the core of this proposal is available.

> This would allow, for example:

> ```javascript
async function getData() {
  var items = await fetchAsync('http://example.com/users');
  return await* items.map(async(item) => {
    return {
      title: item.title, 
      img: (await fetchAsync(item.userDataUrl)).img
    }
  })
}
```

Currently regenerator doesn't seem to support `*` in `await*`.

**Comment by benjamn** [comment]
Interestingly enough, a previous version of the `async` pull request did support `await* arg` as sugar for `await Promise.all(arg)`, but TC39 decided that sugar wasn't very useful, and it evoked a false analogy to `yield*`, so it was explicitly rejected. @lukehoban was present in the meeting where this was decided, if I recall correctly.

I'd be tempted to enable the desugaring with a flag, but of course it requires support from the parser, and you know how much work it can be to get parsing changes accepted :)

Closing for now, but I will gladly reopen this if consensus emerges around supporting `await*` (whatever it ends up meaning).

**Comment by sebmck** [comment]
@benjamn Seems fairly disingenuous to include it in the proposal README if it's already been rejected.

**Comment by benjamn** [comment]
That README predates the decision, and it hasn't been updated because @lukehoban is (I think) no longer working on JS-related stuff at Microsoft. Definitely not disingenous. There's a cost to new syntax, and this feature just didn't meet the benefit threshold. If you can think of something more useful that `await*` could mean, that would be welcome input!

**Comment by benjamn** [comment]
Come to think of it, if you guys want to support `await*` in acorn, I'd be happy to add support for it in Regenerator. If I recall correctly, in the original implementation, the `AwaitExpression` AST node type had a boolean field called `.all`.

**Comment by sebmck** [comment]
@benjamn Is there anywhere the proposal is kept up to date? I don't really care much for `await*` as I agree that it's excessive, just looking into it to see if there was any consensus on it's inclusion.

**Comment by sebmck** [comment]
@benjamn `acorn-6to5` supports it but it's called `delegate` to more inline with `YieldExpression`. `all` makes much more sense though semantically and I'm more than willing to change it.

**Comment by benjamn** [comment]
Yeah, the lack of recorded consensus is frustrating. Here's where I asked about it in the pull request, and no one objected: https://github.com/facebook/regenerator/pull/101#issuecomment-40290760

**Comment by benjamn** [comment]
Reopening. I'm happy to support this in cases where `AwaitExpression` nodes have a truthy `.all` property (though I'm leaving that up to the parser).

**Comment by sebmck** [comment]
Updated in `acorn-6to5`. I'll merge `regenerator-6to5` from upstream and bump the `acorn-6to5` version once the changes are made.

**Comment by lukehoban** [comment]
Yes, the last discussion on the `await*` sugar had concluded that this was likely not necessary for the ES7 timeframe Async/Await proposal.  I think there is general agreement though that it could be added later, and that the semantics described in the proposal is what we would use.  The TC39 discussion notes on this are here: https://github.com/rwaldron/tc39-notes/blob/c61f48cea5f2339a1ec65ca89827c8cff170779b/es6/2014-04/apr-10.md#preview-of-asnycawait

I talked to @bterlson last week about updating the async/await proposal, and I think he's going to try to do that soon along with moving this to the TC39 organization.

**Comment by benjamn** [comment]
Thanks for the update @lukehoban!
