### ISSUE TITLE
return does not work properly inside try/finally

### ISSUE THREAD

**Issue by monsanto** [facebook/regenerator#173]
```
function *foo() {
    for(var i = 0; i < 2; i++) {
        try {
            return i
        } finally {}
    }
}

console.log(foo().next())
```

regenerator will run the loop to completion, and log `{value: 1, done: true}`. It should terminate the loop immediately and print `{value: 0, done: true}`, as io.js does.

**Comment by benjamn** [comment]
This is definitely a bug! As you probably know, `finally` blocks have the ability to override abrupt control flow from the `try` block, but obviously that should only happen if the `finally` block causes an abrupt completion of its own.

I can look at this later today, but if you have time to submit a PR with a failing test case, that would make my work even easier.

**Comment by monsanto** [comment]
Sure, I can cook up some test cases.
