### ISSUE TITLE
Runtime module throws error in a web worker in Safari 8 (Yosemite/iOS) 

### ISSUE THREAD

**Issue by bcamper** [facebook/regenerator#183]
I cannot get the runtime module (as used by Babel etc.) to load in a web worker in Safari 8 (i.e. on Yosemite and iOS 8).

It appears that `Object.prototype.hasOwnProperty` cannot operate on the worker global scope `self` object, and generates this console output when called [here](https://github.com/facebook/regenerator/blob/master/runtime-module.js#L8):

`[Error] TypeError: undefined is not an object (evaluating 'hasOwn.call(g, "regeneratorRuntime")') (worker-gen2.js, line 10)`

I'm unclear if it's valid to call `hasOwnProperty` on a `DedicatedWorkerGlobalScope` object. However, I did find that the following alternative works:

`var hadRuntime = (Object.getOwnPropertyNames(g).indexOf("regeneratorRuntime") > -1);`

If that's an acceptable solution (and I didn't miss something here!), I am happy to submit a PR.

**Comment by benjamn** [comment]
Could these issues be related?
https://github.com/lodash/lodash/pull/458
https://github.com/lodash/lodash/issues/313

If so, then we just need to use `global.self` in a web worker.

**Comment by benjamn** [comment]
Ok, since this only affects https://github.com/facebook/regenerator/blob/master/runtime-module.js, please do submit that PR (with a comment about why this is necessary)!

**Comment by bcamper** [comment]
Thanks, will do.

I meant to bring up the issue that `self` should probably be tested for as well. I see you've already added it :)  Neglected to mention that I tried that to see if it would fix the `hasOwnProperty` exception. But nonetheless I think checking for `self` is the proper way to do it.

**Comment by benjamn** [comment]
It's definitely important to have the right global object, though checking for `self` doesn't help with this bug (according to my quick experiment with web workers).

**Comment by bcamper** [comment]
Yes, sorry, that's what I was trying to say. Looks like both changes are needed. Will submit the PR shortly. Thanks!
