### ISSUE TITLE
Remove built-in support for for-of loop transformation?

### ISSUE THREAD

**Issue by benjamn** [facebook/regenerator#186]
I originally included [support for `for`-`of` loops](https://github.com/facebook/regenerator/blob/94f6e2b66fcf7a30157ca60efb51a23151cbfe66/lib/visit.js#L151-L227) so that I could use them in a demo.

Tools like [Babel](https://github.com/babel/babel/blob/master/src/babel/transformation/templates/for-of.js) do a better job of this.

Regenerator still needs to know what to do if it encounters a `for`-`of` loop inside a generator function (and it contains a `yield`, `return`, etc.), but that's a narrower problem.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by benjamn** [comment]
Now that `regenerator-preset` [uses `babel-plugin-transform-es2015-for-of`](https://github.com/facebook/regenerator/blob/abd543455050ad4c4cef52ca21e694eaa957bfdd/packages/regenerator-preset/index.js#L6), I think this is fixed!
