### ISSUE TITLE
Generator objects should not have own methods

### ISSUE THREAD

**Issue by rauschma** [facebook/regenerator#188]
It goes against the inheritance hierarchy described in the spec [1] and prevents the following trick [2] for preventing generator objects from being closed (by `for-of` etc.):

```js
myGeneratorFunction.prototype.return = undefined;
```

[1] https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generatorfunction-objects
[2] https://mail.mozilla.org/pipermail/es-discuss/2015-March/042255.html

**Comment by benjamn** [comment]
I've known about this for a while, but wasn't sure how much it mattered. Thanks for the example!

**Comment by benjamn** [comment]
Specifically, putting these methods on the prototype means exposing internal `Generator` state in a public way (so that it can be accessed by those methods), which is regrettable, but I suppose inevitable.

**Comment by rauschma** [comment]
This diagram may help (extracted from [1]):
![generator_inheritance](https://cloud.githubusercontent.com/assets/526114/6878030/d5d36a04-d4d7-11e4-9d4b-59c54194c605.jpg)

[1] https://people.mozilla.org/%7Ejorendorff/es6-draft.html#sec-generatorfunction-objects
