### ISSUE TITLE
Runtime & ES3

### ISSUE THREAD

**Issue by zloirock** [facebook/regenerator#190]
After updating `babel` to 5.1 [returned to this problem](https://github.com/babel/babel/issues/167). Cause: [1](https://github.com/facebook/regenerator/blob/master/runtime.js#L148), [2](https://github.com/facebook/regenerator/blob/master/runtime.js#L155). Possible change compression options, but this is another crutch.

**Comment by benjamn** [comment]
Ah, I keep hoping this isn't a problem anymore, but you're right. I'll fix it.
