### ISSUE TITLE
Wrong code generation

### ISSUE THREAD

**Issue by socketpair** [facebook/regenerator#192]
Suppose code:
https://github.com/babel/babel/issues/1279 :

```
async function proxify() {
    try {
        while (true) {
            break;
        }
    }
//    catch(c) {
//        console.log('should never happen');
//    }
    finally {
        console.log(1);
    }
    console.log(2);
}

proxify();
```

This code, as I expect should do ``log(1)`` and ``log(2)`` and then exit. If you try that, it wil really do ``log(1)`` in endless loop. BUG.

BUT(!)(!) If I add exception handler (uncomment lines) bug is not reproduced (!) and everything is work as expected.

**Comment by benjamn** [comment]
Great catch! Fortunately this was a shallow bug with an easy fix.
