### ISSUE TITLE
Feature request: Add an option that's called on every generator replacement

### ISSUE THREAD

**Issue by sebmck** [facebook/regenerator#193]
Babel adds some metadata to `BlockStatement`s containing information about temporary variables that are to be added. Regenerator creates a new block statement so this information is lost. It'd be great if there was a way to provide regenerator a callback that it called with the new and old nodes, this is required in order to fix babel/babel#1268. Thanks!

**Comment by benjamn** [comment]
One unobtrusive way to do this would be to allow an option like `{ newGeneratorFunctions: [] }` whose value would be populated with all the new `Function` objects produced by the transform. You could then grab any nested child property of those functions that you cared about. Sound good?

**Comment by sebmck** [comment]
As in, `newGeneratorFunctions` would include the old and new nodes?

**Comment by sebmck** [comment]
No longer necessary.
