### ISSUE TITLE
Using for...in with anything else(?) than an identifier results in error

### ISSUE THREAD

**Issue by fkling** [facebook/regenerator#194]
This have been addressed already one way or the other, but I couldn't find anything in the issues.

Example:

```js
var foo = {bar: 42, baz: 21};

function* bar() {
  var baz = {};
  for (baz.abc in foo) {
    yield baz.abc;
  }
}
```

Results in:

> AssertionError:  {type: MemberExpression, computed: false, object: [object Object], property: [object Object], range: 72,79, loc: [object Object]} does not match type Identifier

I don't know if it's even possible to handle this case, but if not, it should be noted somewhere.

**Comment by benjamn** [comment]
This shouldn't actually be too hard.

**Comment by benjamn** [comment]
Fixed by 356e84d00d1b3187477ab67e08f07009da271510.

**Comment by fkling** [comment]
Awesome! Yeah, I thought the slightly difficult part would be to not evaluated to LHS expression twice, but it seems like the existing code already considers that.

**Comment by benjamn** [comment]
When I tested it outside of generators, the whole left-hand side gets evaluated again with each iteration, so the translation is fairly easy.

**Comment by fkling** [comment]
Sure, I was referring to something else but realize now that this doesn't apply here anyway (that was specific to my use case).
