### ISSUE TITLE
await* is not supported anymore ?

### ISSUE THREAD

**Issue by matthiasg** [facebook/regenerator#201]
The following code does not transform as expected:

```js
function makeAResult(){
  return new Promise(function(resolve){
    var a = Math.random();
    resolve(a);
  });
}

async function main(){
  var ops = [];

  for(var i=0;i<10;i++){
    ops.push( makeAResult() );
  }

  await* ops;
  console.log('done');
}

main();                                  
```

I had assumed ```await* value``` to be equal to ```await Promise.all(value)``` as it is referred to in a number of places in the net.. e.g http://pouchdb.com/2015/03/05/taming-the-async-beast-with-es7.html.

this is not a big deal, but was await* ever supported ?

**Comment by sebmck** [comment]
It's only supported if the parser you're using supports it.

**Comment by matthiasg** [comment]
I installed regenerator with npm i -g ... The ran it .. So i assume regenerator is using Babel or something and that has to be specified somehow and it defaults to an implementation that doesn't..


-----Original Message-----

**Comment by sebmck** [comment]
The `regenerator` binary uses `esprima-fb` parser that does not support `await*`. Babel uses it's own parser which does support `await*~.

**Comment by matthiasg** [comment]
thanks for the info... i am still a little unsure as to which 'compiler' to use and what the tradeoffs really are .. babel/regenerator/6to5/etc...
