### ISSUE TITLE
Yield in finally, spec confusion as well

### ISSUE THREAD

**Issue by bmeck** [facebook/regenerator#203]
This is an incompatible implementation question, partially brought about by https://code.google.com/p/v8/issues/detail?id=3133 and confusion about what happens when a finally contains a yield. Having yield work inside finally is very valuable and matches the ability to override the completion record like return/throw do, but the spec seems to say that yield does not act this way.

The following code is what is in question:

``` js
function* g() {
  try {
    yield String(111);
  }
  finally {
    yield String(123);
  };
}
let o = g();
console.log('init', o.next());
console.log('preempt ret', o.return());
// v8 issue disagrees, states this should already be done, and cause an error
console.log('after finally yield', o.next());
```

**Comment by benjamn** [comment]
Arbitrary amounts of work, including infinite loops, can already take place in `finally` blocks, in ES5 and long before that. I see no reason why you shouldn't be able to `yield` as many times as you like in a `finally` block. Who disagrees with that? If the argument is from implementation complexity, then it's a non-starter, because Regenerator implements that behavior with no trouble today.

**Comment by bmeck** [comment]
@benjamn the confusion I guess is from the spec stating that .return will set the generate state to closed. And the v8 issue to make the behavior different from what currently is in regenerator

**Comment by benjamn** [comment]
I wonder if the title of that v8 bug is wrong? There's another bug happening there, with the `Generator is already running` error. First, the generator is not already running, and, second, no exception is supposed to be thrown. One is supposed to be able to keep calling `.next()` on a completed generator, one just keeps getting back `{ done: true }`, unless I'm mistaken.

**Comment by benjamn** [comment]
To clarify, I suspect v8 is leaving the internal state set to `"executing"`, when it should be `"suspendedYield"`.

**Comment by benjamingr** [comment]
`finally` has special meaning with regards to `.return` which executes finally blocks.

If you allow `yield`ing the generator in a `finally` block you interfere with that cleanup.

**Comment by benjamn** [comment]
The question is whether there's a reasonable way for the language to prevent that interference, and TC39 has concluded (after numerous discussions that I've been part of) that it's not the job of the language to prevent yielding in a finally block. In particular, putting the generator into the "completed" state while it is still suspended on a yield does nothing to ensure the cleanup finishes as intended.

Preventing yields in finally blocks is, however, a great job for a linting tool!

**Comment by bmeck** [comment]
@benjamingr well the issue as I read in the v8 tracker is that you can yield ala:

```
finally {
  a();
  yield 'not done';
  b();
}
```

and either b will not be executed ever (state is set to complete), or the yield is ignored. Maybe if you have notes / examples you could link it on the v8 tracker then close this?

**Comment by benjamingr** [comment]
@bmeck I'm not sure (sorry for the late response) - if this is not resolved yet we should bring this issue up in es-discuss.

**Comment by bmeck** [comment]
I am fairly certain since yield is just a different completion record it is
allowed to alter behavior just like throw can alter what
.return does. I also would look at the async/await uses of await in finally.

All engines currently are going towards allowing yield in finally. Do you
have a specific requirement for disallowing yield in finally in mind?

**Comment by benjamingr** [comment]
No, I think allowing `yield` in finally and educating developers is what we have to do.

The only argument I can think of against it is cancellation and how `return` works.

**Comment by bmeck** [comment]
That depends on your cancellation semantics,

1. Do you allow cleanup steps to be done via a communication protocol (do
you need to export steps for the consumer)?
2. Is cancellation placed inside of your function logic or outside (via a
scheduler)?

I think for raw generators since the `yield` is in code itself, if they
yield during a finally they should know that a scheduler may/may not
continue the generator. In the case of `async/await` style scheduling, the
scheduler would most likely continue. If your generator is in the middle of
an unsafe operation this could be beneficial.

IE:

```
function* f() {
  try {
    yield create_size_effects();
    return result;
  }
  finally {
    yield undo_side_effects();
    // return result; still happens here
  }
}
let g = f();
g.next();
g.return();
```

Currently will allow `undo_side_effects ` even though it is after a
`return`, and even if it is cancelled via `.return()`.

Anywho I keep playing around with these things and semantics, and I think
yield in finally is good, the only thing I wish was true is that once you
return that only `yield`s within `finally` blocks are invoked, right now
yielding in a finally block can let code escape the finally block.
