### ISSUE TITLE
Rengenerator v0.8.28 is breaking async/await calls when used through babel

### ISSUE THREAD

**Issue by mostafaeweda** [facebook/regenerator#205]
`babel-core` @ v5.1.11 is using `"regenerator": "^0.8.20",` which means with the 28 push, installs it by default --> https://github.com/babel/babel/blob/v5.1.13/package.json#L49

However, the 28 is breaking the simplest async/await calls in that babel version.

/cc @bolinfest @cbosuna

**Comment by sebmck** [comment]
You're linking to a very old commit. This has likely already been resolved with babel/babel#1685.

**Comment by cbosuna** [comment]
Perhaps. But not in the 5.1.x branch. We went from working to broken last night.

**Comment by mostafaeweda** [comment]
`regenerator@0.8.27` works for the `5.1.x`, but not `regenerator@0.8.28`

**Comment by benjamn** [comment]
What's an example of what's broken? Async functions are implemented differently in 0.8.28, but should behave the same.

**Comment by benjamn** [comment]
Fixed by https://github.com/babel/babel/issues/1685. Please update Babel to at least 5.5.3.
