### ISSUE TITLE
Error when compiling: var myFn = function *myFn() {}

### ISSUE THREAD

**Issue by benlambt** [facebook/regenerator#212]
I tried using regenerator to compile koa-router, but it breaks down on this function:
https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L313

###### Input

    var dispatch = function *dispatch(next) {
      debug('%s %s', this.method, this.path);

      var path = router.opts.routerPath || this.routerPath || this.path;
      var matched = router.match(path, this.method);

      if (this.matched) {
        this.matched.push.apply(this.matched, matched.layers);
      } else {
        this.matched = matched.layers;
      }

      if (matched.route) {
        this.route = matched.route;
        this.captures = this.route.captures(path, this.captures);
        this.params = this.route.params(path, this.captures, this.params);

        debug('dispatch %s %s', this.route.path, this.route.regexp);

        next = matched.route.middleware.call(this, next);

        for (var i = 0, l = matched.middleware.length; i < l; i++) {
          next = matched.middleware[i].call(this, next);
        }
      }

      yield *next;
    };

###### Output

    var dispatch = regeneratorRuntime.mark(function dispatch(next) {
      var path, matched, i, l;

      return regeneratorRuntime.wrap(function dispatch$(context$2$0) {
        while (1) switch (context$2$0.prev = context$2$0.next) {
        case 0:
          debug('%s %s', this.method, this.path);

          path = router.opts.routerPath || this.routerPath || this.path;
          matched = router.match(path, this.method);

          if (this.matched) {
            this.matched.push.apply(this.matched, matched.layers);
          } else {
            this.matched = matched.layers;
          }

          if (matched.route) {
            this.route = matched.route;
            this.captures = this.route.captures(path, this.captures);
            this.params = this.route.params(path, this.captures, this.params);

            debug('dispatch %s %s', this.route.path, this.route.regexp);

            next = matched.route.middleware.call(this, next);

            for (i = 0, l = matched.middleware.length; i < l; i++) {
              next = matched.middleware[i].call(this, next);
            }
          }

          return context$2$0.delegateYield(next, "t0", 6);
        case 6:
        case "end":
          return context$2$0.stop();
        }
      }, dispatch, this);
    });

###### Runtime Error
`ReferenceError: dispatch is not defined`

If I change the first line to an anonymous function `var dispatch = function *(next) {`, regenerator gives this output:

    var dispatch = regeneratorRuntime.mark(function callee$1$0(next) {
      var path, matched, i, l;

      return regeneratorRuntime.wrap(function callee$1$0$(context$2$0) {
        while (1) switch (context$2$0.prev = context$2$0.next) {
        case 0:
          debug('%s %s', this.method, this.path);

          path = router.opts.routerPath || this.routerPath || this.path;
          matched = router.match(path, this.method);

          if (this.matched) {
            this.matched.push.apply(this.matched, matched.layers);
          } else {
            this.matched = matched.layers;
          }

          if (matched.route) {
            this.route = matched.route;
            this.captures = this.route.captures(path, this.captures);
            this.params = this.route.params(path, this.captures, this.params);

            debug('dispatch %s %s', this.route.path, this.route.regexp);

            next = matched.route.middleware.call(this, next);

            for (i = 0, l = matched.middleware.length; i < l; i++) {
              next = matched.middleware[i].call(this, next);
            }
          }

          return context$2$0.delegateYield(next, "t0", 6);
        case 6:
        case "end":
          return context$2$0.stop();
        }
      }, callee$1$0, this);
    });

which works.

**Comment by benjamn** [comment]
I'm not sure I understand why the first version causes a ReferenceError. Do you have a stack trace for that error?

**Comment by benjamn** [comment]
I think something must be different between your setup and mine, because `dispatch` is definitely defined, and the original function compiles just fine for me. Perhaps try reducing the test case to the minimal code that causes the problem for you? As it stands, I'm not sure what needs fixing.

**Comment by benlambt** [comment]
Here's the stack trace

    ReferenceError: dispatch is not defined
      at Object.dispatch (/Users/Ben/Dev/Joyxer/node_modules/koa-router/lib/router.js:349:8)
      at Object.callee$1$0$ (/Users/Ben/Dev/Joyxer/node_modules/koa/node_modules/koa-compose/index.js:31:20)
      at tryCatch (/Users/Ben/Dev/Joyxer/node_modules/regenerator/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Ben/Dev/Joyxer/node_modules/regenerator/runtime.js:323:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Ben/Dev/Joyxer/node_modules/regenerator/runtime.js:94:21)
      at onFulfilled (/Users/Ben/Dev/Joyxer/node_modules/co/index.js:65:19)
      at /Users/Ben/Dev/Joyxer/node_modules/co/index.js:54:5
      at Object.co (/Users/Ben/Dev/Joyxer/node_modules/co/index.js:50:10)
      at Object.createPromise (/Users/Ben/Dev/Joyxer/node_modules/co/index.js:30:15)
      at Server.<anonymous> (/Users/Ben/Dev/Joyxer/node_modules/koa/lib/application.js:129:8)
      at Server.emit (events.js:110:17)
      at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
      at Socket.socketOnData (_http_server.js:343:22)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

I'll take another look at the problem

**Comment by benlambt** [comment]
Indeed the code doesn't throw an error when run in isolation...

**Comment by benlambt** [comment]
This seems to be an intermittent error that occasionally goes away on its own. Not sure what's going on, maybe there is a race condition somewhere (I pipe my javascript through regenerator on each node `require` call), and maybe it has nothing to do with regenerator. I'll reopen the issue if I find anything solid.

**Comment by benjamn** [comment]
In case you haven't come across these tools already, there's a project called [gnode](https://github.com/TooTallNate/gnode) that does something maybe similar to what you're doing, and  `require("babel/register")({ whitelist: ["regenerator"] })` is another way of hooking into `require` to transpire Node code. Good luck!
