### ISSUE TITLE
Tasty sandbox bug report

### ISSUE THREAD

**Issue by tchon** [facebook/regenerator#214]
The following code does not transform as expected:
```js
function *range(max, step) {
  var count = 0;
  step = step || 1;

  for (var i = 0; i < max; i += step) {
    count++;
    yield i;
  }

  return count;
}

var gen = range(20, 3), info;

while (!(info = gen.next()).done) {
  console.log(info.value);
}

console.log("steps taken: " + info.value);
```

**Comment by tchon** [comment]
Oops, my bad while using the regenerator page and quickly navigating. Please close.

**Comment by benjamn** [comment]
No problem! I'd rather make it easy to report bugs and occasionally get an accidental one than make it harder and get fewer reports :)
