### ISSUE TITLE
Feature request: transpile function.sent property

### ISSUE THREAD

**Issue by isiahmeadows** [facebook/regenerator#216]
[Proposal, stage 2](https://github.com/allenwb/ESideas/blob/master/Generator%20metaproperty.md)

It's hard to support it without completely transpiling the generator function, but it seems easy to do from Regenerator's end. It's literally holding the last value that went into `next`. Doesn't seem like that much to add support for it in here.

**Comment by benjamn** [comment]
And now it's probably going to move to stage 3: https://github.com/tc39/agendas/blob/master/2015/11.md

Definitely want to support this!
