### ISSUE TITLE
Yield calling Yield combines two variables

### ISSUE THREAD

**Issue by tolmasky** [facebook/regenerator#218]
I originally filed this in Babel, but after looking into it I guess here is the better place? Here is the original bug: https://github.com/babel/babel/issues/2385 (I'm happy to take direction as to which to close). 

Basically, if you have an expression of the form (yield)(yield), it combines both yields into one and you end up with the same value for both. Other double-yield expressions, such as (yield) + (yield)

**Comment by benjamn** [comment]
Fixed by 8edd7ac63c9664597c79372da99cabaf4ffc4427. See also #244. Will be fixed in Babel when https://github.com/babel/babel/pull/4881 is merged.
