### ISSUE TITLE
Wrong naming

### ISSUE THREAD

**Issue by chicoxyzzy** [facebook/regenerator#239]
There is a file named `test/async.es6.js` but it [contains](https://github.com/facebook/regenerator/blob/master/test/async.es6.js#L263-L272) [proposal](https://github.com/tc39/proposal-async-iteration) which is [on stage 1](https://github.com/tc39/ecma262) now so it's not truly es6.
Also [readme](https://github.com/facebook/regenerator/blob/master/README.md) says that es6 is future but it is current spec now.

I can submit PR to fix these inaccuracies if it seems reasonable.

**Comment by benjamn** [comment]
Sorry for the delayed response. Now that #259 is merged, I'm able to devote more time to fixing issues on this repository.

I agree with your analysis. If you have the time, could you change that test file to just `async.js`, make sure the tests pass, and update the README as you suggested?

Thanks for reporting this, and thanks in advance for taking another look at it.

**Comment by chicoxyzzy** [comment]
I'll file a PR later today
