### ISSUE TITLE
Errors inside async function got swallowed (again!)

### ISSUE THREAD

**Issue by coodoo** [facebook/regenerator#245]
I've got a very simple test case showing that errors thrown inside async function can't be caught from outside, I would expect if it's not caught anywhere it will crash the program but seemed doesn't so, is this by design or a bug?

Ps. I'm using `babel 6`.

```js
async function foo(){
	throw new Error('Boom!')
}

// no error caught
foo()

// no error caught
try {
 	foo()
} catch(err) { console.error( err ) }

// works
foo().catch( err => console.log( err ) )

```

**Comment by cesarizu** [comment]
The same thing is happening to me with version `5.8.38`.

**Comment by zloirock** [comment]
It's expected behavior for promises / async functions.

**Comment by coodoo** [comment]
Thanks for pointing that out!

**Comment by cesarizu** [comment]
@zloirock and @coodoo According to the provisional spec, exceptions for promises should be raised and caught with catch blocks.

See: https://tc39.github.io/ecmascript-asyncawait/#abstract-ops-awaited-rejected (point 5)

When a await is rejected then the method should resume with a "throw" completion that should be in turn completed by the catch.

**Comment by cesarizu** [comment]
This example doesn't work either:

```javascript
async function foo(){
    throw new Error('Boom!');
}

async function bar(){
    try {
        await foo();
    } catch(err) { console.error( err ) }
}

bar();
// No error printed to the console
```

**Comment by zloirock** [comment]
> According to the provisional spec, exceptions for promises should be raised and caught with catch blocks.

Wrong. It's about `await` statement. Async errors can't be caught in try / catch.

> This example doesn't work either

[Wrong.](https://goo.gl/pjit2e)

**Comment by cesarizu** [comment]
You are right @zloirock... in my case the problem seems to be more with Firefox not doing anything with **uncaught** rejected promises.
