### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined (starting from version 0.8.43)

### ISSUE THREAD

**Issue by epoberezkin** [facebook/regenerator#246]
See this build job for example: https://travis-ci.org/epoberezkin/ajv/jobs/127242069

0.8.42 works ok.

**Comment by benjamn** [comment]
I think https://github.com/facebook/regenerator/commit/5735674e753f0d16679597cbe5fbfb1860b09c95 may have fixed the problem you're seeing in 0.8.43. Can you try it with 0.8.45?

**Comment by epoberezkin** [comment]
0.8.45 fails too it seems:
https://github.com/epoberezkin/ajv/pull/175
https://travis-ci.org/epoberezkin/ajv/jobs/127330790

**Comment by benjamn** [comment]
Do you know where in your code (or code that you're using) are you including the runtime?

**Comment by epoberezkin** [comment]
https://github.com/epoberezkin/ajv/blob/master/lib/async.js#L95 :

```
var regenerator = require('regenerator');
regenerator.runtime();
```

I think the above was making `regeneratorRuntime` globally available in 0.8.42 and it was used in the transpiled code produced by regenerator:

```
var transpiledCode = regenerator.compile(code).code;
eval(transpiledCode);
```

It's here:
https://github.com/epoberezkin/ajv/blob/master/lib/async.js#L109 and
https://github.com/epoberezkin/ajv/blob/master/lib/compile/index.js#L88

**Comment by epoberezkin** [comment]
0.8.46 still has this issue

**Comment by benjamn** [comment]
I believe https://github.com/facebook/regenerator/commit/d6132cd05d9f56437ed7befc2d9882e286377da2 fixed this in version 0.9.0.

I should also warn you that 0.9.x includes #259, so upgrading *should* be fine, but might introduce some slight changes to your generated code.

**Comment by epoberezkin** [comment]
@benjamn I think the main difference is that 0.8.42 was happily transpiling function bodies (without function keyword) and this version returns syntax error when it meets return outside of function (so it doesn't allow code fragments/function bodies). I can't confirm yet if the original issue was resolved as now it fails earlier during transpilation rather than during execution.

```
SyntaxError: unknown: 'return' outside of function
```

I think not allowing code fragments can be intentional, although it is kind of limiting... I will try to fix it on my end.

**Comment by benjamn** [comment]
Ah, the parser is now `babylon` instead of `esprima-fb`. I should probably make the default behavior more permissive. You can fix this now by calling
```js
require("regenerator").compile(source, {
  babelOptions: {
    parserOpts: {
      allowReturnOutsideFunction: true
    }
  }
})
```

**Comment by benjamn** [comment]
Ok, try it now with `regenerator@0.9.3`?

**Comment by epoberezkin** [comment]
Cool. It works now! https://github.com/epoberezkin/ajv/pull/359
Thank you @benjamn
