### ISSUE TITLE
Wrong return value

### ISSUE THREAD

**Issue by djelas** [facebook/regenerator#255]
The following code does not execute as expected:

``` js
function *example() {
  var value = 0;
  try {
    value = yield;
    value = yield;
  }
  finally {
    return value;
  }
}

var gen = example();
gen.next();
gen.next(1);

var returnValue = gen.return();
console.log("Returned: " + returnValue);
```

The returned value should be equal to 1, instead undefined is returned

**Comment by benjamn** [comment]
Sorry for the delay. I've been waiting until #259 was merged to address pending issues on this repository.

Would you have time to submit a failing test case [here](https://github.com/facebook/regenerator/blob/master/test/tests.es6.js)?
