### ISSUE TITLE
yield* Doesn't work with Async Generators

### ISSUE THREAD

**Issue by Jamesernator** [facebook/regenerator#256]
Using yield\* in an async generator (via babel-transform-regenerator) ends the async generator prematurely, here's an example of where it fails:

``` javascript
async function* one() {
    return 1;
}

async function* two() {
    return (yield* one()) + (yield* one());
}

async function main() {
    console.log((await two().next()).value); // This logs 1
}

main()
```

The above code logs `1` when it should've logged `2`

This the .babelrc for anyone interested:

```
{
    "presets": [
        "es2017",
        "stage-3",
        "stage-2",
        "stage-1",
        "stage-0"
    ],
    "plugins": [
        "syntax-async-generators",
        ["transform-regenerator", {
            "asyncGenerators": true,
            "generators": false,
            "async": false
        }]
    ]
}
```

Changing generators/async to true makes no difference on the behaviour

**Comment by benjamn** [comment]
Would you mind submitting a pull request with a failing test case, if you a minute?

**Comment by Jamesernator** [comment]
I tried it again, it seems to have been fixed between then and now so this can be closed.

**Comment by Jamesernator** [comment]
I'll have a look to see if I can add `yield*` test cases to the test cases as there doesn't seem to be any checking for `yield*` behaviour.
