### ISSUE TITLE
regenerator-runtime doesn't support IE8 or below

### ISSUE THREAD

**Issue by breeswish** [facebook/regenerator#257]
It uses many ES5 only features, for example, https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js#L39

**Comment by benjamn** [comment]
`Object.prototype.hasOwnProperty` is definitely older than ES5, but I know that's just one example. My philosophy is to stick to APIs that can be faithfully polyfilled (e.g. `Object.create`), and you can provide your own polyfills if you're trying to support older browsers.

That said, please feel free to point out (or even submit PRs to fix) ES5-only API usage that can't be polyfilled easily.

**Comment by breeswish** [comment]
Thanks @benjamn , I was using es5-shim and something doesn't work related to regenerator in IE8.
Apologize for my mistake. I just found out that it might not be the issue of regenerator itself. I would like to investigate further :P I will re-open this issue if necessary.
