### ISSUE TITLE
Exceptions in nested async calls are not handled properly

### ISSUE THREAD

**Issue by pugnascotia** [facebook/regenerator#258]
I have a function, `a`, which calls an async function `b`, which in turn calls an async function `c`. I have a `try / catch` around the invocation of `b`, but If `c` throws an exception, the `catch` code is not executed.

I haven't dug into why this might be the case, but I have written a test case:

https://github.com/pugnascotia/regenerator/commit/8deda9932758615a1d4eb63397432c0192c17943

Relevant version from `npm ls`

```
babel-plugin-transform-regenerator@6.11.4
babel-plugin-transform-regenerator@6.16.1
regenerator-runtime@0.9.5
```

**Comment by benjamn** [comment]
Commented on that commit. Let me know if that resolves the issue for you!

**Comment by pugnascotia** [comment]
Huh. Now the test passes, which is annoying as I'm definitely seeing the reported behaviour in our product code. I'll keep trying to replicate it.

**Comment by benjamn** [comment]
Closing for now. Feel free to reopen this if you can reproduce the problem!
