### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by charlierudolph** [facebook/regenerator#272]
Going forward could you please add a changelog so users know what changes come with each new release?

**Comment by benjamn** [comment]
Thanks for the recommendation! Going forward, I promise to add actual release notes to https://github.com/facebook/regenerator/releases (starting with [v0.9.6](https://github.com/facebook/regenerator/releases/tag/v0.9.6)).

**Comment by hulkish** [comment]
@benjamn Just curious for what happened with this? I still see no release notes. This is kind of a hairy one because I want to upgrade babel's usages of `regenerator-runtime` & `regnerator-transform`. See https://github.com/babel/babel/pull/8356/.
