### ISSUE TITLE
[bug] yield* with .return() on parent, missed child's finally block execution

### ISSUE THREAD

**Issue by Andarist** [facebook/regenerator#275]
The following code does not transform as expected:
```js
function* saga(){
    try {
        yield* worker()
    } finally {
        console.log('parent > exit')
    }
}

function* worker(){
    try {
        yield 1 // just stop here
    } finally {
        yield 2
        console.log('child > exit')
    }
}

var t = saga()
t.next() // meet the stoping point
t.return()
t.next()
```

If we run this code in Chrome's console we'll get the following logs:
```js
console.log('child > exit')
console.log('parent > exit')
```
but with regenerator the outcome is only this
```js
console.log('parent > exit')
```

I would be happy to help with fixing this, but at least pointing some starting points in the codebase would be great, as it is not the easiest project to grasp at once

**Comment by benjamn** [comment]
This bug inspired me to spend some quality time with the [**14.4.13 Generator Function Definitions: Runtime Semantics: Evaluation**](https://tc39.github.io/ecma262/#sec-generator-function-definitions-runtime-semantics-evaluation) section of the specification, specifically the part labeled

_YieldExpression_ : **`yield *`** _AssignmentExpression_

Although this bug could have been fixed without significantly rewriting the code that handles `yield*`, I'll sleep better knowing that I've followed the specification exactly.

Thanks for reporting this!

**Comment by Andarist** [comment]
Wow, thanks! Just great work - although I was happy to help with the code I see I wouldnt have a chance to done this right, complex stuff in the commit fixing this!

What's need to be done so this fix is included in the next versions of babel?

**Comment by benjamn** [comment]
It's been a while since I thought about this code, so it wasn't easy for me either!

The `babel-runtime` package currently depends on `regenerator-runtime@^0.10.0`, which is compatible with 0.10.3, so I think these changes should be the default for new installs already?

For what it's worth, I did run the Babel test suite with this version installed, and saw no problems.

**Comment by Andarist** [comment]
Yeah, u are right - new installs are fine! :) Thanks once again.
