### ISSUE TITLE
Tree-shaking transformed generator functions

### ISSUE THREAD

**Issue by rjdestigter** [facebook/regenerator#286]
```
export function *xyz() {}

export function *abc() {}
```

compiles to:
```"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.test = test;
exports.abc = abc;

var _marked = [test, abc].map(regeneratorRuntime.mark);

function test() {
  return regeneratorRuntime.wrap(function test$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
        case "end":
          return _context.stop();
      }
    }
  }, _marked[0], this);
}

function abc() {
  return regeneratorRuntime.wrap(function abc$(_context2) {
    while (1) {
      switch (_context2.prev = _context2.next) {
        case 0:
        case "end":
          return _context2.stop();
      }
    }
  }, _marked[1], this);
}
```

Because of the line `var _marked = [test, abc].map(regeneratorRuntime.mark);` using `Webpack 2` + `UglifyJS` does not _tree shake_  if say only one of the functions is imported in the application.

I wouldn't mind submitting a PR request if someone could point me in the right direction (file) and we think changing this would be a nice update.

**Comment by benjamn** [comment]
This is tricky because `regenerator-transform` runs long before any tree-shaking takes place, so I'm not sure there's anything Regenerator can do to help with this, by itself. Any ideas?

**Comment by rjdestigter** [comment]
What if it compiled to:
```
var _marked_test = regeneratorRuntime.mark(test);
var _marked_abc = regeneratorRuntime.mark(abc);

function abc() {
  return regeneratorRuntime.wrap(function abc$...
    ...
  }, _marked_abc, this);
}

function test() {
  return regeneratorRuntime.wrap(function test$...
    ...
  }, _marked_test, this);
}
```

**Comment by benjamn** [comment]
That would definitely be equivalent, and it would probably be worth the repetition if it helped with tree shaking. Is Webpack smart enough to remove the whole `var _marked_abc = regeneratorRuntime.mark(abc);` line if `_marked_abc` is no longer used?

**Comment by rjdestigter** [comment]
Yes, I'm double checking/testing it at the moment but I'm pretty sure it does

**Comment by benjamn** [comment]
I'm a little worried that `regeneratorRuntime.mark(abc)` by itself is going to prevent the `abc` function from being removed in the first place, but I'd be happy to be wrong!

**Comment by rjdestigter** [comment]
I put the following code inside one module: `generators.js`

```
const regeneratorRuntime = {
  mark: foo => foo,
}

const _marked_abc = regeneratorRuntime.mark(abc)
const _marked_def = regeneratorRuntime.mark(abc)

export function abc () {
  return regeneratorRuntime.wrap(function abc$ (_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          _context.next = 2
          return 1

        case 2:
          _context.next = 4
          return 2

        case 4:
        case 'end':
          return _context.stop()
      }
    }
  }, _marked_abc, this)
}

export function def () {
  return regeneratorRuntime.wrap(function def$ (_context2) {
    while (1) {
      switch (_context2.prev = _context2.next) {
        case 0:
          _context2.next = 2
          return 1

        case 2:
          _context2.next = 4
          return 2

        case 4:
        case 'end':
          return _context2.stop()
      }
    }
  }, _marked_def, this)
}
```

And in my webpack entry:
```
import { abc } from './generators'

abc()
```

I checked the dist file and `def` was not included in the final build using:
```

**Comment by rjdestigter** [comment]
So yes, it seems to be working as expected and `function def()` is _tree shaken_ from the build.

**Comment by benjamn** [comment]
Well ok! I'll have to investigate how that works, for my own curiosity, but I'd be happy to take a pull request that splits the `runtime.mark` calls.

**Comment by benjamn** [comment]
You should probably take a look at [`getRuntimeMarkDecl`](https://github.com/facebook/regenerator/blob/f2579fcb22979661ca95d33b8e1425c5cd106307/packages/regenerator-transform/src/visit.js#L206).

**Comment by rjdestigter** [comment]
Thanks! I'll have a look and see if I can figure it out and test it

**Comment by modosc** [comment]
so i implemented this and in my testing it doesn't work. i think there's a bug in @rjdestigter's test code:
```
const _marked_abc = regeneratorRuntime.mark(abc)
const _marked_def = regeneratorRuntime.mark(abc) <---
```
`def()` isn't ever referenced which is why it's removed.

i'm digging into the webpack side some more to verify because i've already spent almost a day on this and it could potentially cut our bundle size by ~30% (yay `redux-saga`), i'll update with any progress.

**Comment by modosc** [comment]
yep, verified - both the current code and my pr are correctly marked as  `/* unused harmony export */` by webpack but the fact that the function is referenced at all in the body (either via `.map` or individual declaration) seems to prevent it from being removed.

**Comment by benjamn** [comment]
Ah, so it sounds like we would need to remove the `regeneratorRuntime.mark` call if the function it's marking is never used?

**Comment by modosc** [comment]
is there any reason we can't do this:
```
function abc() {
  return regeneratorRuntime.wrap(function abc$...
    ...
  }, regeneratorRuntime.mark(abc), this);
}
```
assuming `regeneratorRuntime.mark` was smart enough to check if it's run already on a function?

**Comment by modosc** [comment]
also fwiw the node8 build fix should go in even if the rest of the pr is scrapped, i'll open a new one next week.

**Comment by benjamn** [comment]
https://github.com/facebook/regenerator/blob/83c5cec9a7945daa82e7431d0ab894d2058ef935/packages/regenerator-runtime/runtime.js#L122

**Comment by modosc** [comment]
i tested my idea and it worked - things are removed correctly by webpack/uglifiyjs2. 

> Unfortunately, functions like regeneratorRuntime.isGeneratorFunction depend on the marking happening before the function is ever called.

yeah, lots of tests fails (even though my app runs ok, probably not using a lot of this functionality).

maybe something like this?
```
exports.abc = regeneratorRuntime.mark(function abc() {
  return regeneratorRuntime.wrap(function abc$...
    ...
  }, abc, this);
})
```

**Comment by Andarist** [comment]
Dont forget to mark those top scope calls as `/*#__PURE__*/` for uglify.

**Comment by modosc** [comment]
@Andarist i added the `/*#__PURE__*/` comments and implemented something very similar to my last suggestion (#301) - everything works now the way i'd expect it to on my application.

**Comment by Andarist** [comment]
@benjamn @rjdestigter this can be closed, tweak for better shakeability was released some time ago
