### ISSUE TITLE
Sandbox bug report

### ISSUE THREAD

**Issue by mattdiamond** [facebook/regenerator#288]
The following code does not transform as expected:
```js
function *range(max, step) {
  var count = 0, regeneratorRuntime;
  step = step || 1;

  for (var i = 0; i < max; i += step) {
    count++;
    yield i;
  }

  return count;
}

var gen = range(20, 3), info;

while (!(info = gen.next()).done) {
  console.log(info.value);
}

console.log("steps taken: " + info.value);
```

In the generated code, the `regeneratorRuntime` variable is declared locally with no modification, masking the regeneratorRuntime library and causing an error.

**Comment by mattdiamond** [comment]
I will accept my bounty of $20k by check or money order

**Comment by hzoo** [comment]
As mentioned in https://twitter.com/mattdiamond/status/852984320830701568, not really a priority to fix
