### ISSUE TITLE
Process polyfill included in builds

### ISSUE THREAD

**Issue by Andarist** [facebook/regenerator#289]
I'm wondering if [this](https://github.com/facebook/regenerator/blob/f2579fcb22979661ca95d33b8e1425c5cd106307/packages/regenerator-runtime/runtime.js#L192-L194) could have been avoided. 

More information can be found in [related thread](https://github.com/facebook/react/pull/9518)

**Comment by benjamn** [comment]
Would this be enough to prevent the polyfill?
```js
if (global.process && global.process.domain) {
  invoke = global.process.domain.bind(invoke);
}
```

**Comment by Andarist** [comment]
Just checked it and created PR with this guard included. 

It still triggers `global`'s polyfill, but this one is really small, so rather a non-issue. This is really weird webpack's implicit behaviour, this whole auto-polyfilling stuff, and cant find any information about this - would like to configure it in the configuration setup. Anyway - this simple 'fix' will let people ship a little bit less code to the browser.
