### ISSUE TITLE
Broken with polyfill.io

### ISSUE THREAD

**Issue by christophehurpeau** [facebook/regenerator#299]
regenerator-runtime: 0.10.5
chrome version 44.0.2403

[This code](https://github.com/facebook/regenerator/blob/ea4de31e4a8151fab67dfa7485b2ac5ede4f8eb3/packages/regenerator-runtime/runtime.js#L417):

```
Gp[toStringTagSymbol] = "Generator";
```

throws:

`Uncaught TypeError: Cannot assign to read only property '__symbol:toStringTag0.123....' of [object Object]`

It doesn't happen in latest chrome.
It's Android users, so we can't ask them to update their browsers...

Do you have any lead that could resolve this ?

Thank you

**Comment by christophehurpeau** [comment]
After investigation, I found that it is linked to polyfill.io: https://github.com/Financial-Times/polyfill-service/issues/1156

**Comment by fstoerkle** [comment]
We are facing the same issue, I am happy to re-open the closed PR https://github.com/facebook/regenerator/pull/300 if that helps

**Comment by christophehurpeau** [comment]
fix in polyfill.io: https://github.com/Financial-Times/polyfill-service/pull/1295
