### ISSUE TITLE
Transform injects marking code above imports

### ISSUE THREAD

**Issue by jridgewell** [facebook/regenerator#304]
Cross posting @niieani's issue from https://github.com/babel/babel/issues/5946

- - - 

**Bug report**

<details>
<summary><b>Input Code</b></summary>

```js
import 'babel-polyfill'

function *generator() {
  yield 1
  yield 2
  yield 3
}

const aGenerator = generator()

// will break in IE 11 or browsers without Symbol support:
for (const a of aGenerator) {
  console.log(a)
}
```
</details>

----

<details>
<summary><b>Output Code</b></summary>

```js
import _regeneratorRuntime from 'babel-runtime/regenerator';

var _marked = [generator].map(_regeneratorRuntime.mark);

import 'babel-polyfill';

function generator() {
  return _regeneratorRuntime.wrap(function generator$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          _context.next = 2;
          return 1;

        case 2:
          _context.next = 4;
          return 2;

        case 4:
          _context.next = 6;
          return 3;

        case 6:
        case 'end':
          return _context.stop();
      }
    }
  }, _marked[0], this);
}

var aGenerator = generator();

for (var _iterator = aGenerator, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
  var _ref;

  if (_isArray) {
    if (_i >= _iterator.length) break;
    _ref = _iterator[_i++];
  } else {
    _i = _iterator.next();
    if (_i.done) break;
    _ref = _i.value;
  }

  var a = _ref;

  console.log(a);
}
```

</details>

----

<details>
<summary><b>Babel Configuration (.babelrc, package.json, cli command)</b></summary>

```js
{
  "presets": [
    ["es2015", {"loose": true, "modules": false}],
    "stage-2"
  ],
  "plugins": [
    ["transform-runtime", {
      "helpers": true,
      "polyfill": false,
      "regenerator": true,
      "moduleName": "babel-runtime"
    }]
  ]
}
```

</details>

----

### Expected Behavior
The `import 'babel-polyfill'` statement should remain on the top of the file. This will ensure that the Symbol polyfill is loaded BEFORE `regenerator-runtime`, because `regenerator` depends on the polyfill being present [at the time of its load](https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js#L17-L20).

### Current Behavior

Currently, `import _regeneratorRuntime from 'babel-runtime/regenerator';` gets placed at the very top of the file, which causes regenerator to create Generator objects with the property named `@@iterator` instead the value of `Symbol.iterator.toString()` generated by the `Symbol` polyfill.

### Possible Solution

Change the order of imports so that `'babel-runtime/regenerator'` is _appended_ to the list of imports, rather than prepended to it.

### Context

I bumped into this bug after adding an `async` function to my entry file. This is when iterators suddenly stopped working in IE 11. Before they worked, since the `babel-polyfill` was executed first, and `Symbol` was already polyfilled. After adding the function, babel started loading `regenerator` before `babel-polyfill`, thus causing `regenerator` to behave differently. This started causing this issue https://github.com/babel/babel/issues/1534. Suffice to say, this was not easy to debug and wasted me a bunch of time, esp. since IE11's debugger is not very friendly. :(

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1 (babel-core 6.25.0)
| node             | 8.1.4
| npm              | 5.2.0
| Operating System | OS X 10.12

**Comment by jridgewell** [comment]
A [second](https://github.com/babel/babel/issues/5893) report of this.

**Comment by Andarist** [comment]
@jridgewell isnt this issue with `babel-plugin-transform-runtime` or something? I believe this import is added [here](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L42-L48).

**Comment by jridgewell** [comment]
Not really. If you look at the input vs output:

```js
import 'babel-polyfill';
//...

// - - -
import _regeneratorRuntime from 'babel-runtime/regenerator';
var _marked = [generator].map(_regeneratorRuntime.mark);
import 'babel-polyfill';
```

Your marking code is inserted above the polyfill, which would still cause the problem. We can fiddle with the regenerator import so it's below the polyfill, but that alone won't fix it.

**Comment by Andarist** [comment]
By running ur given input code with `regenerator-transform` **alone** it gives such output:

<details>
  <summary>Output</summary>

```js
var _marked = /*#__PURE__*/regeneratorRuntime.mark(generator);

import 'babel-polyfill';

function generator() {
  return regeneratorRuntime.wrap(function generator$(_context) {
    while (1) switch (_context.prev = _context.next) {
      case 0:
        _context.next = 2;
        return 1;

      case 2:
        _context.next = 4;
        return 2;

      case 4:
        _context.next = 6;
        return 3;

      case 6:
      case 'end':
        return _context.stop();
    }
  }, _marked, this);
}

const aGenerator = generator();

// will break in IE 11 or browsers without Symbol support:
for (const a of aGenerator) {
  console.log(a);
}
```
</details>

and as imports are getting hoisted up this is not a problem itself. From what I remember its `babel-plugin-transform-runtime` which adds local imports to the `regenerator-runtime` module. `regenerator-transform` doesnt add any imports/requires - it requires global `regeneratorRuntime` object.

**Comment by jridgewell** [comment]
Maybe this has changed recently.

**Comment by Andarist** [comment]
@jridgewell could u reopen any of the mentioned issues in the babel's repository? I can help fixing this, aint sure what the best solution is though - the problem is caused by the way how [`File.prototype.addImport`](https://github.com/babel/babel/blob/6560a29c36fd0f9ef84e78738de11e0477b1384f/packages/babel-core/src/transformation/file/index.js#L192) works, as mentioned above - unshifting the body is causing wrong order of imports in this case. We could assume that imports are always at the top of the file and write new function `File.prototype.appendImport`, which is not ideal and not covering all valid use cases, but aint sure if anything better can be done.

**Comment by VVKot** [comment]
@Andarist Really sorry, forgot to mention you. Please check out this repo:
https://github.com/VVKot/babel-polyfill-issue
In the output file compiled.js import are in the incorrect order.

**Comment by VVKot** [comment]
@Andarist Hello. Will you be able to take a look?
