### ISSUE TITLE
Switch to MIT?

### ISSUE THREAD

**Issue by mikesherov** [facebook/regenerator#316]
Now that React, Jest, and several other are switching, can we switch this repo too? Would be great to coordinate this in time for the Babel 7 release in Babel-polyfill. cc @hzoo

**Comment by benjamn** [comment]
I'm not sure that I have the authority to make this call, though I will note that the [sub-packages](https://github.com/facebook/regenerator/tree/master/packages) are somewhat ambiguously licensed, and have been rewritten significantly by myself and others since I left Facebook.

**Comment by hzoo** [comment]
Yeah that would be great, I had asked about this earlier. And reasons other than ^

- Facebook isn't actively contributing to regenerator, and it's mainly used in/for Babel which is MIT licensed (should move to the babel/meteor/benjman org?
- Ben is still the creator/active maintainer

**Comment by bwhitty** [comment]
Honestly, completely IMO, and employment contract details not withstanding (Ben was working at FB when he wrote this), the "right thing" to do for this project would be to transfer this to @benjamn's org (or possibly babel, or a standalone org). Regenerator is depended on even more than babel-core [1], and is a foundational piece of software across JS ecosystem (which I don't even think the majority of the industry realizes exists).

1: https://npmcharts.com/compare/regenerator-runtime,babel-core

**Comment by hzoo** [comment]
I talked to @zpao about this before (at least moving the repo), I think we had to copy the repo instead of transferring or something (forgot)

**Comment by mikesherov** [comment]
@bwhitty @benjamn are you open to that transfer? Also, @bwhitty do you know who needs to approve the license change? I think there's good community appetite for this change and it's just down to mechanics. Who is authorative here?

**Comment by bwhitty** [comment]
@mikesherov I am certainly not authoritative on this subject, and am not sure who to ping. Maybe bringing this up to Adam Wolff (@dmwlff on Twitter) as I've seen him mentioned as instrumental in getting the React changes through.

**Comment by hzoo** [comment]
I already pinged a few people on this thread ^ and on twitter earlier https://twitter.com/left_pad/status/911806416209489922

**Comment by Chunhao137** [comment]
Any updates on this?

**Comment by zpao** [comment]
I'll ask around about a relicense. And then we can pick up that conversation about the best way to split out from this org. (cc @joelmarcey who mentioned something the other day internally, in case you haven't seen this thread)

**Comment by mikesherov** [comment]
Hey @zpao thanks so much for looking into this, really appreciate this especially since we're close to releasing babel 7 and it would be great to announce an MIT licensed regenerator to go along with it :-)

**Comment by duffman03** [comment]
Is regenerator-runtime truly MIT while regenerator is BSD? If so, can we include a license file in the root of regenerator-runtime?

**Comment by acroyear** [comment]
I personally don't see why a BSD licensed service can't embed an MIT bit of code into a deliverable...but then I'm not a lawyer. :)

Yes, this license is in that file and is appearing in our dist's source-map and that is causing a problem for us in distribution. It more or less makes the re-license of react moot to us unless someone can tell us an alternate way to package that doesn't involve regenerator.

**Comment by bwhitty** [comment]
Hello @zpao if I may ask, I'm wondering whether or not this is moving forward. Thank you!

**Comment by mkallies** [comment]
🙏

**Comment by benjamn** [comment]
Friendly 🏓 @zpao—I know you're probably still waiting on the FB lawyers, but I'm still interested in moving forward here, whenever we get signal.

**Comment by benjamn** [comment]
Just published the MIT-licensed code to npm with these new versions: https://github.com/facebook/regenerator/commit/610e60882404480d5dec4fdbeaa56e1773dbfe37

**Comment by hzoo** [comment]
Made https://github.com/babel/babel/pull/6992 so it will be in the next beta release.
