### ISSUE TITLE
possible  code  change?

### ISSUE THREAD

**Issue by savethegreen7** [facebook/regenerator#326]
In  runtime.js

Is it possible to change the delegate.iterator.return part of the code to delegate.iterator ['return']? There was an identifier error in ie8.

**Comment by benjamn** [comment]
This should be fixed in `regenerator-runtime@0.13.1` thanks to #355 by @loganfsmyth, though please note that this version includes the changes from #353, which might require some adjustment if you were previously relying on a global `regeneratorRuntime` namespace.
