### ISSUE TITLE
Remove `babel-types` dependency and use the one passed to the plugin instead

### ISSUE THREAD

**Issue by hzoo** [facebook/regenerator#328]
So we don't have to keep updating `babel-types` and having incompatibilities with v7.

We'd need to remove the `import * as t from 'babel-types'` in each file in https://github.com/facebook/regenerator/tree/master/packages/regenerator-transform/src

https://github.com/facebook/regenerator/blob/e0d0575d764503cf2817da2c553fd3065c42848f/packages/regenerator-transform/src/index.js#L11-L13

Here we have to pass `context.types` as `t` to all files somehow (babel-types is passed so each babel plugin already)? Not sure the best way to do this other than wrapping files in a function with the passed `t`

**Comment by benjamn** [comment]
Implemented in #329! Hope you like my solution to the `context.types`-passing problem.
