### ISSUE TITLE
`Function("...")` causes unsafe-eval CSP violation in Chrome extension

### ISSUE THREAD

**Issue by deltaidea** [facebook/regenerator#336]
I'm trying to use [react-form](https://github.com/react-tools/react-form) in my Chrome extension options page. It has `regenerator-runtime` as the transitive dependency that throws the error, so I figured I'll create an issue here.

Thanks for your time! I appreciate your support of the JS community.

## Expected Behavior

`regenerator-runtime` works silently like a good boy.

## Actual Behavior

```js
require("regenerator-runtime") // Uncaught EvalError
```

Offending line: `node_modules/regenerator-runtime/runtime-module.js:10`

```js
var g = (function() { return this })() || Function("return this")();
```

Version: `regenerator-runtime@0.11.1`

Full error:

> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:".

## Environment

Chrome extension Options page, Chrome 63.0.3239.132 (64-bit), Windows 10

**Comment by deltaidea** [comment]
https://github.com/facebook/regenerator/pull/292#issuecomment-298097498

> ... it should be safe as long as you don't blindly concatenate all your JS together with the `"use strict";` at the top ...

Unfortunately, strict mode is enforced in the extension environment. I'm guessing the same is true in other secure sandboxes such as Chrome apps and Atom plugins.

**Comment by JakeChampion** [comment]
@deltaidea I think the line can be changed to:
```
var g = (function() { return this ? this : typeof self !== undefined ? self : undefined})() || Function("return this")();
```

**Comment by deltaidea** [comment]
Yeah, that works, thank you!

Can you guys please take a look and tell if this is a reasonable fix?
I'm gonna replace this package with a modified copy for now in my project.

**Comment by JakeChampion** [comment]
It should be a reasonable fix, `self` is the global object and works in Browsers' main thread as well as workers (Service Workers, Web Workers, Shared Workers etc).

**Comment by ijsnow** [comment]
This is also a problem with firefox extensions
