### ISSUE TITLE
cannot install regenerator-transform

### ISSUE THREAD

**Issue by azopyros** [facebook/regenerator#338]
Hello,

`npm i --save regenerator-transform` is blocked on this line : 
`⸨░░░░░░░░░░░░░░░░░░⸩ ⠴ fetchMetadata: sill resolveWithNewModule regenerator-transform@0.12.3 checking installable status`

I'm on a Mac@10.11.6, Node@8.4.0, NPM@5.6.0

Thanks

**Comment by benjamn** [comment]
Pretty sure this is an npm problem, not anything to do with this library.

**Comment by azopyros** [comment]
Pause for the week-end, now it works, I don't know why, but it does 😄 

Thanks
