### ISSUE TITLE
regenerator-runtime & ES3

### ISSUE THREAD

**Issue by fan776783** [facebook/regenerator#341]
Mabe replace line 336  `delegate.iterator.return` to `delegate.iterator['return']` in runtime.js for old IE support

**Comment by afreidz** [comment]
trying to support legacy enterprise applications that use IE8 rendering.  this recently started causing errors for us.

**Comment by benjamn** [comment]
This should be fixed in `regenerator-runtime@0.13.1` thanks to #355 by @loganfsmyth, though please note that this version includes the changes from #353, which might require some adjustment if you were previously relying on a global `regeneratorRuntime` namespace.
