### ISSUE TITLE
AST location information lost when emitting yield replacement (and others)

### ISSUE THREAD

**Issue by loganfsmyth** [facebook/regenerator#342]
See in this sample from http://sokra.github.io/source-map-visualization for a sample async function passed through Babel.
<img width="838" alt="screen shot 2018-02-16 at 10 46 43 am" src="https://user-images.githubusercontent.com/132260/36323717-b9cc9fe0-1306-11e8-9474-f3171c42a69d.png">

Note how the `return` before `doAsync` is blue instead of white, and the right side shows no generated mapping for the `await`.

This specific example is for https://github.com/facebook/regenerator/blob/58c0eca04145da79c263194a605ca5a6294a72b4/packages/regenerator-transform/src/emit.js#L1189

Where essentially ideally it would do
```
let ret = t.returnStatement(arg || null);
ret.loc = expr.loc;
self.emit(ret);
```
so the location information from the yield expression is carried over onto the `return` statement.

Depending how ambitious we want to be, this probably also comes up in a few other places where regenerator creates new AST nodes, like all of these cases: https://github.com/facebook/regenerator/blob/58c0eca04145da79c263194a605ca5a6294a72b4/packages/regenerator-transform/src/emit.js#L1162
the replacement UpdateExpression will not have the location information that the original node did, which may not be ideal.

Think I've got someone who wants to look into making a PR for this. Handling the `return` at least would be ideal, but it might be good to account for the other cases too.

**Comment by benjamn** [comment]
This seems doable! In general, statements that do not contain any `yield` expressions get left alone, so their `.loc` information should be intact, but I would imagine any newly created AST nodes will be missing `.loc` information. If preserving the `.loc` property is all that has to happen for source maps to be useful within `async` and/or generator functions, that's great news.

**Comment by loganfsmyth** [comment]
Yeah, I think it at partially depends on how ambitious someone wants to be with fixing things. This could be split into multiple tasks. In this case at least fixing the `return` allows users to who are stepping through code to step onto an `await` expression statement properly, because when they step to the `return` it will map back to `await`. 

Right now you can set a breakpoint on `await doAsync()` and it will take the closes point and stop at `doAsync()`, but you can't actually reach it stepping one statement at a time because it steps to the `return` and the return doesn't map to a useful location. At least in FF.
