### ISSUE TITLE
+= and other update operators should read their left-hand side _before_ yielding

### ISSUE THREAD

**Issue by loganfsmyth** [facebook/regenerator#345]
You can thank @jakearchibald for this one: https://twitter.com/jaffathecake/status/999269332889763840

```
let x = 0;

function* test() {
  x += yield; 
}

var gen = test();
gen.next();
x += 1;
console.log(x);

gen.next(2);
console.log(x); 
```
should log
```
1
2
```
but with Regenerator it logs
```
1
3
```

Regenerator outputs:
```
function test() {
  return regeneratorRuntime.wrap(function test$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          _context.next = 2;
          return;

        case 2:
          x += _context.sent;

        case 3:
        case "end":
          return _context.stop();
      }
    }
  }, _marked, this);
}
```

Executable example visible in [the Babel REPL](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBAHhC8EAYDcAoFAzArgOwMZgEsB7bAKgjBAGcwAKASggG8UJoIBqeATwJGAAmSCCgC-aAG4BDAE4QA5iGxwK1OvVSLsAOmwgo61DC4QAjKlwkqRUNuBF5tKBrRbd-ugCYXl7Ndv2js7CQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=) Enabling evaluation and toggling `es2015` will alternate between browser-native and regenerator-compiled behavior.

**Comment by benjamn** [comment]
Fun!

**Comment by lovetingyuan** [comment]
https://www.youtube.com/watch?v=bfxglBVSNDI&app=desktop
```javascript
let x = 0;
async function test() {
  x += await 2;
  console.log(x); // should be 2, but regenerator will output 3
}
test();
x += 1;
console.log(x);
```

**Comment by benjamn** [comment]
Although I assigned this to myself, anyone else should feel free to comment here if they have time to look at this in the next week.
