### ISSUE TITLE
Package distributions are not licensed

### ISSUE THREAD

**Issue by honzajavorek** [facebook/regenerator#354]
Hi @benjamn 👋 The code of the `regenerator` monorepo is licensed under MIT, and that's great. But according to MIT, the license text needs to be attached everywhere:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

The npm packages as they're published and distributed, do not comply with this as they do not contain the license files. Effectively, without the full license text they're proprietary code and cannot be used by anyone who cares about licenses. The SPDX identifier in the `package.json` is not satisfactory (not only) for the reasons mentioned above. There are two solutions to this:

1. Upgrade to Lerna@3, as it has the licensing built-in now
2. Copy & paste the root license to all projects in the `packages` directory, so it gets picked up by npm during publishing, and to re-publish all of them with a new patch version.

We did the second with Babel as it was faster than to upgrade Lerna, atm. Especially in this particular case, when there are just 3 packages, I think just copypasting the license to those would be a very fast and simple solution.

For more information, see https://github.com/lerna/lerna/pull/1465#issuecomment-405184876, https://github.com/babel/babel/pull/7308#issuecomment-367615152, https://github.com/babel/babel/pull/8409#issuecomment-415379558.

-----

Side note: I found some related issues, which I believe are obsolete and I think they can be closed right away: https://github.com/facebook/regenerator/pull/215 by @rafaelstz, https://github.com/facebook/regenerator/issues/298 by @krotscheck

**Comment by Bosch-Eli-Black** [comment]
Any chance of getting this fixed? It looks like this is still happening in the latest versions.

**Comment by hrieke** [comment]
Upvote.
Com'on don't be a lazy programmer...
