### ISSUE TITLE
Global variable is not defined in babel 6 / webpack 3

### ISSUE THREAD

**Issue by lerayne** [facebook/regenerator#363]
I'm using babel v6.26.3 and webpack 3.12.0

If I call regenerrator-runtime as `import 'regenerator-runtime/runtime'` to define a global variable the code results to be
START
```javascript
/***/ "./node_modules/regenerator-runtime/runtime.js":
/***/ (function(module, exports, __webpack_require__) {

/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

var regeneratorRuntime = (function (exports) {
  "use strict";

  var Op = Object.prototype;
```

END
```javascript
  // Regardless of whether this script is executing as a CommonJS module
  // or not, return the runtime object so that we can declare the variable
  // regeneratorRuntime in the outer scope, which allows this module to be
  // injected easily by `bin/regenerator --include-runtime script.js`.
  return exports;

}(
  // If this script is executing as a CommonJS module, use module.exports
  // as the regeneratorRuntime namespace. Otherwise create a new empty
  // object. Either way, the resulting object will be used to initialize
  // the regeneratorRuntime variable at the top of this file.
   true ? module.exports : {}
));


/***/ }),
```

Which means "regeneratorRuntime" is never registered as a global variable and the code stops to work.

This is happening in 0.13.1, I moved to 0.12.1 and everything is working fine there.

**Comment by lerayne** [comment]
Then probably this readme file should be changed accordingly: https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/README.md

It also goes to npm page of the regenerator-runtime and gets people like me confused

**Comment by mj1856** [comment]
This appears to also breaks Jest tests.  Per [these docs](https://jestjs.io/docs/en/getting-started#using-babel), one is supposed to add `regenerator-runtime` (not `@babel/plugin-transform-runtime`), but it expects `regeneratorRuntime` to be on the global scope.

Tests fail with `ReferenceError: regeneratorRuntime is not defined` after updating regenerator-runtime to 0.13.1.

Tried with both Jest version 23.6.0 and 24.0.0-alpha.9.

**Comment by vincro** [comment]
> Tried with both Jest version 23.6.0 and 24.0.0-alpha.9.

Did you figure out a fix for this besides a downgrade?

**Comment by mj1856** [comment]
@vincro  - nope.  I've set `"regenerator-runtime": "0.12.1"` in my package.json for now.

**Comment by xjamundx** [comment]
Ouch, yeah many outdated docs on this in the world. Just go bit.
