### ISSUE TITLE
Function(...) is not a function   TypeError: Function(...) is not a function

### ISSUE THREAD

**Issue by gaoxiaomumu** [facebook/regenerator#373]
"version": "0.13.2"

![image](https://user-images.githubusercontent.com/21135585/57757729-b1fc2600-7728-11e9-9389-3d45eecdbb4e.png)

![image](https://user-images.githubusercontent.com/21135585/57757583-5893f700-7728-11e9-80c8-b716e4ca3069.png)

**Comment by benjamn** [comment]
What's unclear about the comment? Either do not load `regenerator-runtime` in strict mode (preferred), or make sure your code runs in a JS environment with a standard implementation of the `Function` constructor.
