### ISSUE TITLE
Property name expected type of string but got null [Error]

### ISSUE THREAD

**Issue by tenjojeremy** [facebook/regenerator#391]
Following code produces the error:

```js
const hello = async () => {
  const he = { ll: '2' }
  const { ll } = he
}
```
`babel config`

```js
module.exports = {
  presets: [
    [
      require('@babel/preset-env'),
      {
        targets: 'defaults, not ie <= 11, not edge > 0, not IE_Mob 11',
        modules: false
      }
    ],
    require('@babel/preset-react')
  ],
  plugins: [
    require('react-hot-loader/babel'),
    require('@babel/plugin-transform-regenerator'),
    require('@babel/plugin-syntax-dynamic-import'),
    require('@babel/plugin-syntax-throw-expressions'),
    require('@babel/plugin-transform-runtime'),
    require('babel-plugin-styled-components')
  ],
  env: {
    production: {
      plugins: [require('babel-plugin-transform-react-remove-prop-types')]
    }
  }
}
```

`package.json`

```json
  "dependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-syntax-throw-expressions": "^7.8.3",
    "@babel/plugin-transform-regenerator": "^7.8.7",
    "@babel/plugin-transform-runtime": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/preset-react": "^7.9.4",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^25.1.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-styled-components": "^1.10.7",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "react-hot-loader": "^4.12.20"
  },
```

`node` version `v12.13.1`

Thanks

More context https://github.com/facebook/regenerator/pull/390

**Comment by nicolo-ribaudo** [comment]
@tenjojeremy / @liuliangsir All the browsers with destructuring support also support generators. What is the use case for regenerator when you are not transpiling destructuring?

**Comment by tenjojeremy** [comment]
@nicolo-ribaudo I removed this package and my app still works, turn out I wasn't using it correctly  but don't need it. I no longer need the fix but it seems other people do.

**Comment by liuliangsir** [comment]
> I removed this package and my app still works

@tenjojeremy , which package? Sadly, I have been running into the issue above for some time. [Here](https://github.com/liuliangsir/codemirror-lint-eslint) is a minimal reproducible example.

**Comment by tenjojeremy** [comment]
> > I removed this package and my app still works
> 
> @tenjojeremy , which package? Sadly, I have been running into the issue above for some time. [Here](https://github.com/liuliangsir/codemirror-lint-eslint) is a minimal reproducible example.

I removed 'require('@babel/plugin-transform-regenerator')'

**Comment by nicolo-ribaudo** [comment]
@liuliangsir Does your targets support destructuring?
- Yes -> Then they also support generators, so you can remove `@babel/plugin-transform-regenerator`
- No -> Then you need to add `@babel/plugin-transform-destructuring`

**Comment by tenjojeremy** [comment]
https://github.com/facebook/regenerator/issues/391#issuecomment-617095947 solves the issue

**Comment by adamreisnz** [comment]
I am not using `@babel/plugin-transform-regenerator`, and event when I specify only target chrome 80, it still throws this error. Any other ideas for fixing it?

**Comment by MwumLi** [comment]
> @liuliangsir Does your targets support destructuring?
> 
> * Yes -> Then they also support generators, so you can remove `@babel/plugin-transform-regenerator`
> * No -> Then you need to add `@babel/plugin-transform-destructuring`

if targets support destructuring, why is this error reportedn when add `@babel/plugin-transform-regenerator`

**Comment by nicolo-ribaudo** [comment]
Because this plugin assumes that destructuring has been compiled. What's your use case for compiling generators but not destructuring?
