### ISSUE TITLE
regenerator-runtime new version 0.13.11 not tagged as latest

### ISSUE THREAD

**Issue by UlrichHP** [facebook/regenerator#633]
I use `yarn upgrade-interactive` to update my packages.
 
This plugin showed me the new version of regenerator-runtime (v0.13.11).
The update was a success.

But now, when i rerun `yarn upgrade-interactive`, the plugin propose me to update regenerator-runtime to the previous version, 0.13.10, which is tagged as latest.

**Comment by benjamn** [comment]
I intentionally publish these packages to npm using the `next` tag at first, to get some initial downloads and make sure nothing is terribly broken, before triggering mass upgrades by promoting to `latest`.

As far as I'm concerned, then, it's good news when the only problem anyone reports is that the new versions have not been promoted to `latest` yet, as you did here. Thank you!

Closing now that I've tagged the new `regenerator-{runtime,transform,preset}` patch versions as `latest`.
