### ISSUE TITLE
What changed in version 0.14.0?

### ISSUE THREAD

**Issue by catamphetamine** [facebook/regenerator#687]
Hi.
There doesn't seem to be no CHANGELOG or description on the Releases tab.
So what has changed in version 0.14.0?
Is there anything breaking, as semantic versioning suggests?

**Comment by benjamn** [comment]
As explained in the version bump commit for `regenerator-runtime` package (30771b77fc6132fa97c892e818cd0bc113491abf), I was a tiny bit concerned PR #636 (which fixed a bug) might have introduced a new case where `yield*` could throw (instead of silently iterating over nothing).

**Comment by catamphetamine** [comment]
Thanks. So basically it's:

> The minor version bump is due to the new ability of `yield*` to throw when given a non-iterable argument.

Which translates to me as "no changes unless your project used `yield*` syntax".
